###
POST http://localhost:8000/api/register
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=admin4&email=admin4@admin4.com&password=password&password_confirmation=password

# product get /product/id
GET http://localhost:8000/api/products/3

###
GET http://localhost:8000/api/products

# # product get
# GET http://localhost:8000/api/product

###
GET http://localhost:8000/api/products/search/sadaf

###
POST http://localhost:8000/api/products
Content-Type: application/json
Accept: application/json

{
  "name":"sadaf",
  "description":"dsaf",
  "slug":"dsaf",
  "price":"12.22"
}

###
PUT http://localhost:8000/api/products/2
Content-Type: application/json
Accept: application/json

{
  "name":"sadaf",
  "description":"dsaf",
  "slug":"dsaf",
  "price":"12.00"
}

###
DELETE http://localhost:8000/api/products/2

###
GET http://localhost:8000/api/first
